bugzilla:
    url: "https://bugzilla.mozilla.org/rest/"
    creator: "infosec+rra2json@mozilla.com"
    rra:
        product: "Enterprise Information Security"
        component: "Rapid Risk Analysis"
        assignees:
            - gdestuynder@mozilla.com
            - jclaudius@mozilla.com
            - culucenk@mozilla.com
        cache: "/tmp/rra_assignees.pickle"
    va:
        product: "Enterprise Information Security"
        component: "Vulnerability Assessment"
        assignees:
            - gdestuynder@mozilla.com
            - jclaudius@mozilla.com
            - culucenk@mozilla.com
        cache: "/tmp/va_assignees.pickle"